### ISSUE TITLE
Missing rev 0.5 schematics

### ISSUE THREAD

**Issue by Syntec1** [nonarkitten/amiga_replacement_project#11]
Hi,

Maybe I'm not looking in the correct place but can it be that I'm missing the schematics for rev0.5 board?
I see a it jumps from rev 0.4 to rev 0.7.

**Comment by nonarkitten** [comment]
For which board?

**Comment by Syntec1** [comment]
Thanks for replying, for the reagnus 0.5 rev board as I would like to build a few for my amigas that I have.

**Comment by nonarkitten** [comment]
These are not ready for people to make yet, unless you're doing so to help out with development.
