### ISSUE TITLE
[Question] Scope/extent of the project

### ISSUE THREAD

**Issue by ceztko** [nonarkitten/amiga_replacement_project#12]
I noticed a service manual was recently [uploaded](https://github.com/nonarkitten/amiga_replacement_project/commit/f5ce4f37d928cf23de9732860090bc579528b7eb). So I am asking what's exactly the scope/extent of the project, if it can span over schematics/service manuals of all the amiga models or there's a limit. For example, I just found this [folder](http://www.kaiiv.de/servicemanuals/) which contains a lot of material which might be preserved here, if the material gets organized properly.

**Comment by nonarkitten** [comment]
It's right in the readme.
"To make replacements for all the custom chips of the AMIGA, useable in any real AMIGA."

We're not about preservation, but we have local copies of a lot of things simply for reference. The service manual for the A500+ includes the equations for Gayle which we used to test-out Gary.
