### ISSUE TITLE
ECS agnus schematics

### ISSUE THREAD

**Issue by mithrendal** [nonarkitten/amiga_replacement_project#7]
super cool that we got the OCS Agnus schematics signed by jay miner and joe decuir.  

https://github.com/nonarkitten/amiga_replacement_project/blob/master/agnus/MOS_Agnus_compressed.pdf

Is there any chance that someone has also some drawings for ECS agnus too? Maybe somewhere in the attic … 

or maybe some old document which shows the differences ?

@hazydave do you possibly have an idea who we can ask about old dusty ECS schematic drawings?

**Comment by buffeebeta** [comment]
The remaining copies are being held by Jeri Ellsworth, and good luck getting those from her ☹

I also have Alice which is basically just 2MB Agnus with the tweaks for 32-bit DRAM and Double-CAS. With enough time, you could extrapolate between the two.

**Comment by mithrendal** [comment]
before Amiga belonged to Commodore, Atari gave Amiga a helping credit so that it could survive and pay employees for some more months. As part of the credit deal Amiga had to grant Atari the right to use the schematics of the custom chips but only in case the credit could not be payed back….

in this video https://www.youtube.com/watch?v=DQeizK_0oBE at pos 35:15 Amiga employees mention that they intentionally modified the schematic drawings which were given to Atari. This should make the  schematics basically not working and therefore useless in case that atari would be so mean and lay off all amiga employees and only grab the custom chip schematics…  I bet they thought that atari wanted only to buy the custom chips and hardware of the AmigaComputer and were not interested at all into the situation of the Amiga employees 

the question is now … which version of OCS schematics  in this project do we have. the intentionally broken ones or the correct ones ? 

@JeriEllsworth 
Jeri, do you know by chance if the schematics are the real ones?

**Comment by nonarkitten** [comment]
Agnus came from Joe himself, so those are correct.
